# Generated by Django 5.2.15 on 2026-07-31 10:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionnaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivraisonManuelle',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison', models.DateField(verbose_name='Date')),
                ('client_nom', models.CharField(max_length=150, verbose_name='Client')),
                ('client_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro client')),
                ('nature_colis', models.CharField(max_length=255, verbose_name='Nature du colis')),
                ('lieu_depart', models.CharField(max_length=255, verbose_name='Départ')),
                ('lieu_arrivee', models.CharField(max_length=255, verbose_name='Arrivée')),
                ('observations', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observations')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (FCFA)')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('numero_facture', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Numéro de facture')),
                ('date_facture', models.DateTimeField(blank=True, null=True, verbose_name='Date de facturation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_manuelles_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livraison manuelle',
                'verbose_name_plural': 'Livraisons manuelles',
                'ordering': ['-date_livraison', '-date_creation'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
