# Generated by Django 4.2.25 on 2025-11-30 19:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DCL",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adresse_depart",
                    models.CharField(max_length=255, verbose_name="Adresse de depart"),
                ),
                (
                    "adresse_destination",
                    models.CharField(
                        max_length=255, verbose_name="Adresse de destination"
                    ),
                ),
                (
                    "latitude_depart",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitude de depart  "
                    ),
                ),
                (
                    "longitude_depart",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitude de depart"
                    ),
                ),
                (
                    "latitude_destination",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Latitude de destination"
                    ),
                ),
                (
                    "longitude_destination",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Longitude de destination"
                    ),
                ),
                (
                    "Contact_destinateur",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_colis",
                    models.TextField(
                        help_text="Donnez un aperçu détaillé du contenu du colis",
                        verbose_name="Description du colis",
                    ),
                ),
                (
                    "poids_colis",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, "Le poids doit être supérieur à 0"
                            )
                        ],
                        verbose_name="Poids du colis (kg)",
                    ),
                ),
                (
                    "valeur_colis",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "La valeur ne peut pas être négative"
                            )
                        ],
                        verbose_name="Valeur du colis (FCFA)",
                    ),
                ),
                (
                    "date_demande",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Date de la demande",
                    ),
                ),
                (
                    "date_recuperation",
                    models.DateTimeField(
                        help_text="Date souhaitée pour la récupération du colis",
                        verbose_name="Date et heure de récupération",
                    ),
                ),
                (
                    "type_course",
                    models.CharField(
                        choices=[("EXPRESSE", "Expresse"), ("CLASSIQUE", "Classique")],
                        default="CLASSIQUE",
                        max_length=10,
                        verbose_name="Type de course",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            (
                                "EN_ATTENTE",
                                "1. En attente – En attente de proposition de prix vous allez recevoir un appel",
                            ),
                            (
                                "VALIDATION_CLIENT",
                                "2. Validation client – Le client Valider le prix proposé",
                            ),
                            (
                                "VALIDATION_LIVREUR",
                                "3. Validation livreur – En attente d’acceptation du livreur",
                            ),
                            (
                                "LIVREUR_ROUTE",
                                "4. Livreur en route pour récupération du colis",
                            ),
                            ("RECEPTION_COLIS", "5. Récupération du colis"),
                            ("LIVRAISON_EN_ROUTE", "6. Livraison en route"),
                            ("TERMINEE", "7. Livrée – Livraison terminée"),
                            ("ANNULEE", "8. Annulée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=30,
                        verbose_name="Statut de la demande",
                    ),
                ),
                (
                    "photo_colis1",
                    models.ImageField(
                        blank=True,
                        help_text="Téléchargez une photo du colis (max 5 Mo)",
                        null=True,
                        upload_to="photos_colis/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"],
                                message="Format de fichier non supporté. Utilisez jpg, jpeg, png ou gif.",
                            )
                        ],
                        verbose_name="Photo du colis 1",
                    ),
                ),
                (
                    "photo_colis2",
                    models.ImageField(
                        blank=True,
                        help_text="Téléchargez une deuxième photo du colis (optionnel)",
                        null=True,
                        upload_to="photos_colis/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"],
                                message="Format de fichier non supporté. Utilisez jpg, jpeg, png ou gif.",
                            )
                        ],
                        verbose_name="Photo du colis 2",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Toute instruction spécifique pour le livreur",
                        null=True,
                        verbose_name="Instructions supplémentaires",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "cout_livraison",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Coût de livraison",
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
                (
                    "coursier",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "livreur"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livraisons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coursier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de coursier",
                "verbose_name_plural": "Demandes de coursiers",
                "ordering": ["-date_demande"],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
