# Generated by Django 5.1.4 on 2026-06-11 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0002_clientinvite_dcl_client_invite_alter_dcl_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcl',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', ' En attente'), ('VALIDATION_CLIENT', '  Prix validé par le client'), ('VALIDATION_LIVREUR', ' Validation livreur'), ('LIVREUR_ROUTE', ' Livreur en route pour récupération du colis'), ('RECEPTION_COLIS', ' Récupération du colis'), ('LIVRAISON_EN_ROUTE', ' Livraison en route'), ('TERMINEE', ' Livrée'), ('ANNULEE', ' Annulée')], default='EN_ATTENTE', max_length=30, verbose_name='Statut de la demande'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type_notif', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Alerte')], default='info', max_length=20, verbose_name='Type')),
                ('lien', models.CharField(blank=True, max_length=500, null=True, verbose_name='Lien')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Demande.dcl', verbose_name='Demande')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
