# Generated by Django 4.2.25 on 2026-06-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0003_alter_dcl_statut_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcl',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective'),
        ),
        migrations.AddField(
            model_name='dcl',
            name='signature_destinataire',
            field=models.TextField(blank=True, help_text='Signature en base64 (PNG)', null=True, verbose_name='Signature du destinataire'),
        ),
    ]
