# Generated by Django 4.2.25 on 2026-07-03 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0004_add_signature_date_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcl',
            name='unite_poids',
            field=models.CharField(choices=[('Kg', 'Kg (Kilogramme)'), ('T', 'T (Tonne)')], default='Kg', max_length=2, verbose_name='Unité de poids'),
        ),
        migrations.AlterField(
            model_name='dcl',
            name='poids_colis',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, 'Le poids doit être supérieur à 0')], verbose_name='Poids du colis'),
        ),
    ]
