# Generated by Django 5.2.15 on 2026-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0005_add_unite_poids_extend_poids_colis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcl',
            name='date_facture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de facturation'),
        ),
        migrations.AddField(
            model_name='dcl',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Numéro de facture'),
        ),
        migrations.CreateModel(
            name='FactureCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('dernier_numero', models.PositiveIntegerField(default=0, verbose_name='Dernier numéro émis')),
            ],
            options={
                'verbose_name': 'Compteur de facture',
                'verbose_name_plural': 'Compteurs de facture',
                'unique_together': {('annee', 'mois')},
            },
        ),
    ]
