# Generated by Django 5.2.15 on 2026-07-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0006_dcl_date_facture_dcl_numero_facture_facturecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcl',
            name='signature_expediteur',
            field=models.TextField(blank=True, help_text='Signature en base64 (PNG) — capturée uniquement pour les demandes invité (sans compte client)', null=True, verbose_name="Signature de l'expéditeur"),
        ),
    ]
