# Generated by Django 5.2.15 on 2026-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0007_dcl_signature_expediteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcl',
            name='designation_facture',
            field=models.CharField(blank=True, help_text='Description du colis à facturer, saisie par le gestionnaire à la première génération de la facture — définitive au même titre que le numéro de facture', max_length=255, null=True, verbose_name='Désignation (facture)'),
        ),
    ]
