# Generated by Django 4.2.25 on 2025-11-30 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Livreur",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                (
                    "is_available",
                    models.CharField(
                        choices=[("OCCUPER", "OCCUPER"), ("LIBRE", "LIBRE")],
                        default="LIBRE",
                        max_length=10,
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "date_mise_a_jour_coordonnees",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Date de mise à jour des coordonnées",
                    ),
                ),
                (
                    "date_sauvegarde_coordonnees",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date de sauvegarde des coordonnées",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "livreur"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
