# Generated by Django 4.2.25 on 2025-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Livreur", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livreur",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude "),
        ),
        migrations.AlterField(
            model_name="livreur",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude "),
        ),
    ]
